name: google_home
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fl_chart: ^0.64.0
  dio: ^5.3.3
  flutter_riverpod: ^2.4.3
  riverpod_annotation: ^2.2.0
  freezed_annotation: ^2.4.1
  rive: ^0.11.17
  dbus: ^0.7.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  riverpod_generator: ^3.0.0-dev.3
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  riverpod_lint: ^2.3.0
  freezed: ^2.4.5

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/rive/
